### ISSUE TITLE
`filter` sometimes leaves `null` in output

### ISSUE THREAD

**Issue by matthewleon** [paf31/purescript-lists-fast#3]
Add the following line to the test file:

`logShow <<< filter odd $ 0..10`

get an error:

```
/Users/mleon/proj/purescript-lists-fast/output/Data.Show/foreign.js:4
  return n.toString();
           ^

TypeError: Cannot read property 'toString' of null
    at exports.showIntImpl (/Users/mleon/proj/purescript-lists-fast/output/Data.Show/foreign.js:4:12)
    at /Users/mleon/proj/purescript-lists-fast/output/Data.List.Types/index.js:135:29
    at /Users/mleon/proj/purescript-lists-fast/output/Data.Function/index.js:16:24
    at $tco_loop (/Users/mleon/proj/purescript-lists-fast/output/Data.List.Types/index.js:88:38)
    at /Users/mleon/proj/purescript-lists-fast/output/Data.List.Types/index.js:95:31
    at /Users/mleon/proj/purescript-lists-fast/output/Data.List.Types/index.js:127:79
    at /Users/mleon/proj/purescript-lists-fast/output/Data.List.Types/index.js:158:151
    at /Users/mleon/proj/purescript-lists-fast/output/Control.Monad.Eff.Console/index.js:14:53
    at Object.__do [as main] (/Users/mleon/proj/purescript-lists-fast/output/Test.Main/index.js:64:87)
    at Object.<anonymous> (/private/var/folders/5d/mm0ndksj04j8vp1jfx2nzyp40000gn/T/pulp-test117112-75589-o8nszy.71zc.js:1:84)
* ERROR: Subcommand terminated with exit code 1
```

This shouldn't be too hard to isolate.

**Comment by matthewleon** [comment]
Looks like it's easy to end up with a Cons cell with a `null` `value0` at the end.
